
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\076\000\002\002\004\000\002\002\003\000\002\022" +
    "\002\000\002\003\006\000\002\023\002\000\002\003\005" +
    "\000\002\004\004\000\002\004\003\000\002\005\003\000" +
    "\002\005\003\000\002\005\003\000\002\005\003\000\002" +
    "\005\003\000\002\005\003\000\002\005\003\000\002\005" +
    "\003\000\002\006\005\000\002\011\003\000\002\011\003" +
    "\000\002\011\003\000\002\011\003\000\002\007\006\000" +
    "\002\010\005\000\002\024\002\000\002\025\002\000\002" +
    "\012\012\000\002\026\002\000\002\013\005\000\002\013" +
    "\002\000\002\027\002\000\002\030\002\000\002\014\011" +
    "\000\002\031\002\000\002\032\002\000\002\033\002\000" +
    "\002\034\002\000\002\015\016\000\002\016\007\000\002" +
    "\017\007\000\002\020\005\000\002\020\005\000\002\020" +
    "\005\000\002\020\005\000\002\020\005\000\002\020\005" +
    "\000\002\020\005\000\002\020\005\000\002\020\005\000" +
    "\002\020\005\000\002\020\005\000\002\020\005\000\002" +
    "\020\004\000\002\020\004\000\002\020\003\000\002\021" +
    "\003\000\002\021\003\000\002\021\003\000\002\021\003" +
    "\000\002\021\003\000\002\021\003\000\002\021\003\000" +
    "\002\021\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\161\000\004\040\004\001\002\000\032\004\uffff\006" +
    "\uffff\007\uffff\010\uffff\011\uffff\012\uffff\013\uffff\014\uffff" +
    "\015\uffff\040\uffff\041\ufffd\043\uffff\001\002\000\004\002" +
    "\007\001\002\000\004\002\000\001\002\000\004\002\001" +
    "\001\002\000\004\041\163\001\002\000\030\004\021\006" +
    "\016\007\035\010\022\011\017\012\013\013\025\014\032" +
    "\015\031\040\004\043\023\001\002\000\032\004\ufff5\006" +
    "\ufff5\007\ufff5\010\ufff5\011\ufff5\012\ufff5\013\ufff5\014\ufff5" +
    "\015\ufff5\040\ufff5\041\ufff5\043\ufff5\001\002\000\004\043" +
    "\ufff0\001\002\000\004\043\161\001\002\000\032\004\ufff9" +
    "\006\ufff9\007\ufff9\010\ufff9\011\ufff9\012\ufff9\013\ufff9\014" +
    "\ufff9\015\ufff9\040\ufff9\041\ufff9\043\ufff9\001\002\000\004" +
    "\036\uffe4\001\002\000\004\036\147\001\002\000\032\004" +
    "\ufff2\006\ufff2\007\ufff2\010\ufff2\011\ufff2\012\ufff2\013\ufff2" +
    "\014\ufff2\015\ufff2\040\ufff2\041\ufff2\043\ufff2\001\002\000" +
    "\004\036\uffea\001\002\000\004\036\131\001\002\000\004" +
    "\024\126\001\002\000\004\041\125\001\002\000\004\043" +
    "\uffef\001\002\000\032\004\ufff3\006\ufff3\007\ufff3\010\ufff3" +
    "\011\ufff3\012\ufff3\013\ufff3\014\ufff3\015\ufff3\040\ufff3\041" +
    "\ufff3\043\ufff3\001\002\000\032\004\ufff4\006\ufff4\007\ufff4" +
    "\010\ufff4\011\ufff4\012\ufff4\013\ufff4\014\ufff4\015\ufff4\040" +
    "\ufff4\041\ufff4\043\ufff4\001\002\000\032\004\021\006\016" +
    "\007\035\010\022\011\017\012\013\013\025\014\032\015" +
    "\031\040\004\041\ufffa\043\023\001\002\000\004\043\uffed" +
    "\001\002\000\004\043\uffee\001\002\000\032\004\ufff6\006" +
    "\ufff6\007\ufff6\010\ufff6\011\ufff6\012\ufff6\013\ufff6\014\ufff6" +
    "\015\ufff6\040\ufff6\041\ufff6\043\ufff6\001\002\000\032\004" +
    "\ufff8\006\ufff8\007\ufff8\010\ufff8\011\ufff8\012\ufff8\013\ufff8" +
    "\014\ufff8\015\ufff8\040\ufff8\041\ufff8\043\ufff8\001\002\000" +
    "\004\036\uffe1\001\002\000\032\004\ufff7\006\ufff7\007\ufff7" +
    "\010\ufff7\011\ufff7\012\ufff7\013\ufff7\014\ufff7\015\ufff7\040" +
    "\ufff7\041\ufff7\043\ufff7\001\002\000\004\036\040\001\002" +
    "\000\004\043\023\001\002\000\026\016\uffe0\017\uffe0\021" +
    "\uffe0\035\uffe0\036\uffe0\043\uffe0\044\uffe0\045\uffe0\046\uffe0" +
    "\047\uffe0\001\002\000\026\016\045\017\051\021\043\035" +
    "\055\036\046\043\052\044\056\045\044\046\047\047\053" +
    "\001\002\000\026\016\045\017\051\021\043\035\055\036" +
    "\046\043\052\044\056\045\044\046\047\047\053\001\002" +
    "\000\036\020\uffc9\021\uffc9\022\uffc9\023\uffc9\025\uffc9\026" +
    "\uffc9\027\uffc9\030\uffc9\031\uffc9\032\uffc9\033\uffc9\034\uffc9" +
    "\037\uffc9\042\uffc9\001\002\000\036\020\uffc6\021\uffc6\022" +
    "\uffc6\023\uffc6\025\uffc6\026\uffc6\027\uffc6\030\uffc6\031\uffc6" +
    "\032\uffc6\033\uffc6\034\uffc6\037\uffc6\042\uffc6\001\002\000" +
    "\026\016\045\017\051\021\043\035\055\036\046\043\052" +
    "\044\056\045\044\046\047\047\053\001\002\000\036\020" +
    "\uffc8\021\uffc8\022\uffc8\023\uffc8\025\uffc8\026\uffc8\027\uffc8" +
    "\030\uffc8\031\uffc8\032\uffc8\033\uffc8\034\uffc8\037\uffc8\042" +
    "\uffc8\001\002\000\036\020\uffcc\021\uffcc\022\uffcc\023\uffcc" +
    "\025\uffcc\026\uffcc\027\uffcc\030\uffcc\031\uffcc\032\uffcc\033" +
    "\uffcc\034\uffcc\037\uffcc\042\uffcc\001\002\000\036\020\uffc5" +
    "\021\uffc5\022\uffc5\023\uffc5\025\uffc5\026\uffc5\027\uffc5\030" +
    "\uffc5\031\uffc5\032\uffc5\033\uffc5\034\uffc5\037\uffc5\042\uffc5" +
    "\001\002\000\036\020\uffcb\021\uffcb\022\uffcb\023\uffcb\025" +
    "\uffcb\026\uffcb\027\uffcb\030\uffcb\031\uffcb\032\uffcb\033\uffcb" +
    "\034\uffcb\037\uffcb\042\uffcb\001\002\000\036\020\uffc7\021" +
    "\uffc7\022\uffc7\023\uffc7\025\uffc7\026\uffc7\027\uffc7\030\uffc7" +
    "\031\uffc7\032\uffc7\033\uffc7\034\uffc7\037\uffc7\042\uffc7\001" +
    "\002\000\034\020\064\021\061\022\067\023\066\025\063" +
    "\026\062\027\071\030\065\031\073\032\070\033\060\034" +
    "\072\042\110\001\002\000\026\016\045\017\051\021\043" +
    "\035\055\036\046\043\052\044\056\045\044\046\047\047" +
    "\053\001\002\000\036\020\uffca\021\uffca\022\uffca\023\uffca" +
    "\025\uffca\026\uffca\027\uffca\030\uffca\031\uffca\032\uffca\033" +
    "\uffca\034\uffca\037\uffca\042\uffca\001\002\000\036\020\uffcd" +
    "\021\uffcd\022\uffcd\023\uffcd\025\uffcd\026\uffcd\027\uffcd\030" +
    "\uffcd\031\uffcd\032\uffcd\033\uffcd\034\uffcd\037\uffcd\042\uffcd" +
    "\001\002\000\026\016\045\017\051\021\043\035\055\036" +
    "\046\043\052\044\056\045\044\046\047\047\053\001\002" +
    "\000\026\016\045\017\051\021\043\035\055\036\046\043" +
    "\052\044\056\045\044\046\047\047\053\001\002\000\026" +
    "\016\045\017\051\021\043\035\055\036\046\043\052\044" +
    "\056\045\044\046\047\047\053\001\002\000\026\016\045" +
    "\017\051\021\043\035\055\036\046\043\052\044\056\045" +
    "\044\046\047\047\053\001\002\000\026\016\045\017\051" +
    "\021\043\035\055\036\046\043\052\044\056\045\044\046" +
    "\047\047\053\001\002\000\026\016\045\017\051\021\043" +
    "\035\055\036\046\043\052\044\056\045\044\046\047\047" +
    "\053\001\002\000\026\016\045\017\051\021\043\035\055" +
    "\036\046\043\052\044\056\045\044\046\047\047\053\001" +
    "\002\000\026\016\045\017\051\021\043\035\055\036\046" +
    "\043\052\044\056\045\044\046\047\047\053\001\002\000" +
    "\026\016\045\017\051\021\043\035\055\036\046\043\052" +
    "\044\056\045\044\046\047\047\053\001\002\000\026\016" +
    "\045\017\051\021\043\035\055\036\046\043\052\044\056" +
    "\045\044\046\047\047\053\001\002\000\026\016\045\017" +
    "\051\021\043\035\055\036\046\043\052\044\056\045\044" +
    "\046\047\047\053\001\002\000\026\016\045\017\051\021" +
    "\043\035\055\036\046\043\052\044\056\045\044\046\047" +
    "\047\053\001\002\000\036\020\064\021\061\022\067\023" +
    "\066\025\uffd2\026\uffd2\027\uffd2\030\uffd2\031\uffd2\032\uffd2" +
    "\033\uffd2\034\uffd2\037\uffd2\042\uffd2\001\002\000\036\020" +
    "\064\021\061\022\067\023\066\025\063\026\062\027\071" +
    "\030\065\031\073\032\070\033\060\034\uffcf\037\uffcf\042" +
    "\uffcf\001\002\000\036\020\064\021\061\022\067\023\066" +
    "\025\uffd4\026\uffd4\027\uffd4\030\uffd4\031\uffd4\032\uffd4\033" +
    "\uffd4\034\uffd4\037\uffd4\042\uffd4\001\002\000\036\020\064" +
    "\021\061\022\067\023\066\025\uffd1\026\uffd1\027\uffd1\030" +
    "\uffd1\031\uffd1\032\uffd1\033\uffd1\034\uffd1\037\uffd1\042\uffd1" +
    "\001\002\000\036\020\uffd8\021\uffd8\022\uffd8\023\uffd8\025" +
    "\uffd8\026\uffd8\027\uffd8\030\uffd8\031\uffd8\032\uffd8\033\uffd8" +
    "\034\uffd8\037\uffd8\042\uffd8\001\002\000\036\020\uffd7\021" +
    "\uffd7\022\uffd7\023\uffd7\025\uffd7\026\uffd7\027\uffd7\030\uffd7" +
    "\031\uffd7\032\uffd7\033\uffd7\034\uffd7\037\uffd7\042\uffd7\001" +
    "\002\000\036\020\064\021\061\022\067\023\066\025\uffd3" +
    "\026\uffd3\027\uffd3\030\uffd3\031\uffd3\032\uffd3\033\uffd3\034" +
    "\uffd3\037\uffd3\042\uffd3\001\002\000\036\020\uffda\021\uffda" +
    "\022\067\023\066\025\uffda\026\uffda\027\uffda\030\uffda\031" +
    "\uffda\032\uffda\033\uffda\034\uffda\037\uffda\042\uffda\001\002" +
    "\000\036\020\064\021\061\022\067\023\066\025\uffd6\026" +
    "\uffd6\027\071\030\065\031\073\032\070\033\uffd6\034\uffd6" +
    "\037\uffd6\042\uffd6\001\002\000\036\020\064\021\061\022" +
    "\067\023\066\025\uffd5\026\uffd5\027\071\030\065\031\073" +
    "\032\070\033\uffd5\034\uffd5\037\uffd5\042\uffd5\001\002\000" +
    "\036\020\uffd9\021\uffd9\022\067\023\066\025\uffd9\026\uffd9" +
    "\027\uffd9\030\uffd9\031\uffd9\032\uffd9\033\uffd9\034\uffd9\037" +
    "\uffd9\042\uffd9\001\002\000\036\020\064\021\061\022\067" +
    "\023\066\025\063\026\062\027\071\030\065\031\073\032" +
    "\070\033\uffd0\034\uffd0\037\uffd0\042\uffd0\001\002\000\004" +
    "\043\uffdf\001\002\000\004\043\112\001\002\000\004\024" +
    "\117\001\002\000\004\037\uffde\001\002\000\004\037\115" +
    "\001\002\000\004\040\004\001\002\000\032\004\uffdd\006" +
    "\uffdd\007\uffdd\010\uffdd\011\uffdd\012\uffdd\013\uffdd\014\uffdd" +
    "\015\uffdd\040\uffdd\041\uffdd\043\uffdd\001\002\000\026\016" +
    "\045\017\051\021\043\035\055\036\046\043\052\044\056" +
    "\045\044\046\047\047\053\001\002\000\034\020\064\021" +
    "\061\022\067\023\066\025\063\026\062\027\071\030\065" +
    "\031\073\032\070\033\060\034\072\037\uffeb\001\002\000" +
    "\034\020\064\021\061\022\067\023\066\025\063\026\062" +
    "\027\071\030\065\031\073\032\070\033\060\034\072\037" +
    "\122\001\002\000\036\020\uffc4\021\uffc4\022\uffc4\023\uffc4" +
    "\025\uffc4\026\uffc4\027\uffc4\030\uffc4\031\uffc4\032\uffc4\033" +
    "\uffc4\034\uffc4\037\uffc4\042\uffc4\001\002\000\036\020\uffce" +
    "\021\uffce\022\uffce\023\uffce\025\uffce\026\uffce\027\uffce\030" +
    "\uffce\031\uffce\032\uffce\033\uffce\034\uffce\037\uffce\042\uffce" +
    "\001\002\000\004\041\ufffb\001\002\000\036\002\ufffe\004" +
    "\ufffe\005\ufffe\006\ufffe\007\ufffe\010\ufffe\011\ufffe\012\ufffe" +
    "\013\ufffe\014\ufffe\015\ufffe\040\ufffe\041\ufffe\043\ufffe\001" +
    "\002\000\026\016\045\017\051\021\043\035\055\036\046" +
    "\043\052\044\056\045\044\046\047\047\053\001\002\000" +
    "\034\020\064\021\061\022\067\023\066\025\063\026\062" +
    "\027\071\030\065\031\073\032\070\033\060\034\072\042" +
    "\130\001\002\000\054\004\uffec\006\uffec\007\uffec\010\uffec" +
    "\011\uffec\012\uffec\013\uffec\014\uffec\015\uffec\016\uffec\017" +
    "\uffec\021\uffec\035\uffec\036\uffec\040\uffec\041\uffec\043\uffec" +
    "\044\uffec\045\uffec\046\uffec\047\uffec\001\002\000\026\016" +
    "\045\017\051\021\043\035\055\036\046\043\052\044\056" +
    "\045\044\046\047\047\053\001\002\000\034\020\064\021" +
    "\061\022\067\023\066\025\063\026\062\027\071\030\065" +
    "\031\073\032\070\033\060\034\072\037\133\001\002\000" +
    "\004\042\134\001\002\000\032\004\uffdc\006\uffdc\007\uffdc" +
    "\010\uffdc\011\uffdc\012\uffdc\013\uffdc\014\uffdc\015\uffdc\040" +
    "\uffdc\041\uffdc\043\uffdc\001\002\000\004\036\136\001\002" +
    "\000\026\016\045\017\051\021\043\035\055\036\046\043" +
    "\052\044\056\045\044\046\047\047\053\001\002\000\034" +
    "\020\064\021\061\022\067\023\066\025\063\026\062\027" +
    "\071\030\065\031\073\032\070\033\060\034\072\037\140" +
    "\001\002\000\004\040\uffe9\001\002\000\004\040\004\001" +
    "\002\000\034\004\uffe5\005\144\006\uffe5\007\uffe5\010\uffe5" +
    "\011\uffe5\012\uffe5\013\uffe5\014\uffe5\015\uffe5\040\uffe5\041" +
    "\uffe5\043\uffe5\001\002\000\032\004\uffe8\006\uffe8\007\uffe8" +
    "\010\uffe8\011\uffe8\012\uffe8\013\uffe8\014\uffe8\015\uffe8\040" +
    "\uffe8\041\uffe8\043\uffe8\001\002\000\004\040\uffe7\001\002" +
    "\000\004\040\004\001\002\000\032\004\uffe6\006\uffe6\007" +
    "\uffe6\010\uffe6\011\uffe6\012\uffe6\013\uffe6\014\uffe6\015\uffe6" +
    "\040\uffe6\041\uffe6\043\uffe6\001\002\000\004\043\150\001" +
    "\002\000\004\037\151\001\002\000\004\042\152\001\002" +
    "\000\032\004\uffdb\006\uffdb\007\uffdb\010\uffdb\011\uffdb\012" +
    "\uffdb\013\uffdb\014\uffdb\015\uffdb\040\uffdb\041\uffdb\043\uffdb" +
    "\001\002\000\004\036\154\001\002\000\026\016\045\017" +
    "\051\021\043\035\055\036\046\043\052\044\056\045\044" +
    "\046\047\047\053\001\002\000\034\020\064\021\061\022" +
    "\067\023\066\025\063\026\062\027\071\030\065\031\073" +
    "\032\070\033\060\034\072\037\156\001\002\000\004\040" +
    "\uffe3\001\002\000\004\040\004\001\002\000\032\004\uffe2" +
    "\006\uffe2\007\uffe2\010\uffe2\011\uffe2\012\uffe2\013\uffe2\014" +
    "\uffe2\015\uffe2\040\uffe2\041\uffe2\043\uffe2\001\002\000\004" +
    "\042\162\001\002\000\032\004\ufff1\006\ufff1\007\ufff1\010" +
    "\ufff1\011\ufff1\012\ufff1\013\ufff1\014\ufff1\015\ufff1\040\ufff1" +
    "\041\ufff1\043\ufff1\001\002\000\036\002\ufffc\004\ufffc\005" +
    "\ufffc\006\ufffc\007\ufffc\010\ufffc\011\ufffc\012\ufffc\013\ufffc" +
    "\014\ufffc\015\ufffc\040\ufffc\041\ufffc\043\ufffc\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\161\000\006\002\004\003\005\001\001\000\006\022" +
    "\010\023\007\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\030\003\017\004" +
    "\023\005\027\006\014\007\033\011\013\012\035\014\032" +
    "\015\011\016\026\017\025\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\027\152\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\024\134\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\030\003\017\004\123\005\027\006\014" +
    "\007\033\011\013\012\035\014\032\015\011\016\026\017" +
    "\025\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\031\036\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\007\040\001\001" +
    "\000\004\032\041\001\001\000\006\020\053\021\047\001" +
    "\001\000\006\020\122\021\047\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\020\120\021\047\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\020" +
    "\056\021\047\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\020\106\021\047\001\001\000\006\020\105\021" +
    "\047\001\001\000\006\020\104\021\047\001\001\000\006" +
    "\020\103\021\047\001\001\000\006\020\102\021\047\001" +
    "\001\000\006\020\101\021\047\001\001\000\006\020\100" +
    "\021\047\001\001\000\006\020\077\021\047\001\001\000" +
    "\006\020\076\021\047\001\001\000\006\020\075\021\047" +
    "\001\001\000\006\020\074\021\047\001\001\000\006\020" +
    "\073\021\047\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\033\110\001\001\000\004\010\112\001\001" +
    "\000\002\001\001\000\004\034\113\001\001\000\002\001" +
    "\001\000\004\003\115\001\001\000\002\001\001\000\006" +
    "\020\117\021\047\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\020\126\021\047\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\020\131\021\047" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\020\136\021\047\001\001" +
    "\000\002\001\001\000\004\025\140\001\001\000\004\003" +
    "\141\001\001\000\004\013\142\001\001\000\002\001\001" +
    "\000\004\026\144\001\001\000\004\003\145\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\020" +
    "\154\021\047\001\001\000\002\001\001\000\004\030\156" +
    "\001\001\000\004\003\157\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    public AnalisadorSemantico semantico = new AnalisadorSemantico();
    public GeradorDeCodigo gerador = new GeradorDeCodigo();

    public boolean erroSintatico = false;

    public java.util.Stack<String> pilhaRotulos = new java.util.Stack<String>();

    public java.util.Stack<java.util.List<String>> pilhaIncremento =
        new java.util.Stack<java.util.List<String>>();
    public String promover(AtributosExpressao operando, String tipoResultado) {
        if ("real".equals(tipoResultado) && "int".equals(operando.tipo)) {
            String destino = gerador.novoRegistrador();
            gerador.emitir("CVTIR", destino + ", " + operando.registrador);
            return destino;
        }
        return operando.registrador;
    }
    public String tipoComum(AtributosExpressao a, AtributosExpressao b) {
        return ("real".equals(a.tipo) || "real".equals(b.tipo)) ? "real" : "int";
    }
    public AtributosExpressao comparar(String operador, String mnemonico,
                                       AtributosExpressao a, AtributosExpressao b,
                                       int linha, int coluna) {
        String tipo = semantico.verificarComparacao(operador, a.tipo, b.tipo, linha, coluna);
        String comum = tipoComum(a, b);
        String destino = gerador.novoRegistrador();
        gerador.emitir(mnemonico, destino + ", " + promover(a, comum) + ", " + promover(b, comum));
        return new AtributosExpressao(tipo, destino);
    }
    public AtributosExpressao calcular(String operador, String mnemonico,
                                       AtributosExpressao a, AtributosExpressao b,
                                       int linha, int coluna) {
        String tipo = semantico.verificarAritmetica(operador, a.tipo, b.tipo, linha, coluna);
        String destino = gerador.novoRegistrador();
        gerador.emitir(mnemonico, destino + ", " + promover(a, tipo) + ", " + promover(b, tipo));
        return new AtributosExpressao(tipo, destino);
    }
    public AtributosExpressao combinar(String operador, String mnemonico,
                                       AtributosExpressao a, AtributosExpressao b,
                                       int linha, int coluna) {
        String tipo = semantico.verificarLogica(operador, a.tipo, b.tipo, linha, coluna);
        String destino = gerador.novoRegistrador();
        gerador.emitir(mnemonico, destino + ", " + a.registrador + ", " + b.registrador);
        return new AtributosExpressao(tipo, destino);
    }
    public void atribuir(String nome, AtributosExpressao valor, int linha, int coluna) {
        String tipoDestino = semantico.usar(nome, linha, coluna);
        semantico.verificarAtribuicao(tipoDestino, valor.tipo, nome, linha, coluna);
        String origem = valor.registrador;
        if (semantico.exigeConversao(tipoDestino, valor.tipo)) {
            String convertido = gerador.novoRegistrador();
            gerador.emitir("CVTIR", convertido + ", " + origem);
            origem = convertido;
        }
        gerador.emitir("STORE", semantico.rotuloDe(nome) + ", " + origem);
    }

    public void syntax_error(Symbol s) {
        erroSintatico = true;
        int linha = (s.left >= 0) ? s.left : -1;
        String tok = (s.value != null) ? s.value.toString() : "fim de arquivo";
        if (linha > 0) {
            System.err.println("Erro Sintatico [linha " + linha +
                               ", col " + s.right +
                               "]: token inesperado -> " + tok);
        } else {
            System.err.println("Erro Sintatico [fim do arquivo]: esperava mais tokens");
        }
    }

    public void unrecovered_syntax_error(Symbol s) throws Exception {
        int linha = (s.left >= 0) ? s.left : -1;
        String tok = (s.value != null) ? s.value.toString() : "fim de arquivo";
        if (linha > 0) {
            throw new Exception("Erro fatal [linha " + linha +
                                "]: analise interrompida em -> " + tok);
        } else {
            throw new Exception("Erro fatal [fim do arquivo]: esperava '}' para fechar o bloco");
        }
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= bloco 
            {
              Object RESULT =null;
		 gerador.emitir("HALT"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // NT$0 ::= 
            {
              Object RESULT =null;
 semantico.abrirEscopo(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // bloco ::= LBRACE NT$0 lista_cmd RBRACE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 semantico.fecharEscopo(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloco",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // NT$1 ::= 
            {
              Object RESULT =null;
 semantico.abrirEscopo(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$1",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // bloco ::= LBRACE NT$1 RBRACE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 semantico.fecharEscopo(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloco",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // lista_cmd ::= cmd lista_cmd 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_cmd",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // lista_cmd ::= cmd 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_cmd",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // cmd ::= decl 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cmd",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // cmd ::= atrib 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cmd",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // cmd ::= se_senao 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cmd",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // cmd ::= enquanto 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cmd",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // cmd ::= para 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cmd",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // cmd ::= escrever 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cmd",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // cmd ::= ler 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cmd",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // cmd ::= bloco 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cmd",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // decl ::= tipo ID SEMI 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 semantico.declarar(i, t, ileft, iright); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("decl",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // tipo ::= T_INT 
            {
              String RESULT =null;
		 RESULT = "int";  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // tipo ::= T_REAL 
            {
              String RESULT =null;
		 RESULT = "real"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // tipo ::= T_CHR 
            {
              String RESULT =null;
		 RESULT = "chr";  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // tipo ::= T_STR 
            {
              String RESULT =null;
		 RESULT = "str";  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // atrib ::= ID ATTR expr SEMI 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AtributosExpressao e = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 atribuir(i, e, ileft, iright); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atrib",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // atrib_inc ::= ID ATTR expr 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AtributosExpressao e = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 atribuir(i, e, ileft, iright); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atrib_inc",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // NT$2 ::= 
            {
              Object RESULT =null;
 gerador.emitirComentario("comando if: avaliacao da condicao"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$2",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // NT$3 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AtributosExpressao c = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

                 semantico.verificarCondicao(c.tipo, "if", cleft, cright);
                 String rotuloFalso = gerador.novoRotulo();
                 gerador.emitir("JMPF", c.registrador + ", " + rotuloFalso);
                 pilhaRotulos.push(rotuloFalso);
             
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$3",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // se_senao ::= IF NT$2 LPAR expr RPAR NT$3 bloco opt_senao 
            {
              Object RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		AtributosExpressao c = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		 gerador.emitirRotulo(pilhaRotulos.pop()); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("se_senao",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // NT$4 ::= 
            {
              Object RESULT =null;

                  String rotuloFalso = pilhaRotulos.pop();
                  String rotuloFim = gerador.novoRotulo();
                  gerador.emitir("JMP", rotuloFim);
                  gerador.emitirRotulo(rotuloFalso);
                  pilhaRotulos.push(rotuloFim);
              
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$4",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // opt_senao ::= ELSE NT$4 bloco 
            {
              Object RESULT =null;
              // propagate RESULT from NT$4
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opt_senao",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // opt_senao ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opt_senao",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // NT$5 ::= 
            {
              Object RESULT =null;

                 gerador.emitirComentario("comando while: inicio do laco");
                 String rotuloInicio = gerador.novoRotulo();
                 gerador.emitirRotulo(rotuloInicio);
                 pilhaRotulos.push(rotuloInicio);
             
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$5",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // NT$6 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AtributosExpressao c = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

                 semantico.verificarCondicao(c.tipo, "while", cleft, cright);
                 String rotuloFim = gerador.novoRotulo();
                 gerador.emitir("JMPF", c.registrador + ", " + rotuloFim);
                 pilhaRotulos.push(rotuloFim);
             
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$6",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // enquanto ::= WHILE NT$5 LPAR expr RPAR NT$6 bloco 
            {
              Object RESULT =null;
              // propagate RESULT from NT$6
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		AtributosExpressao c = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		
                 String rotuloFim = pilhaRotulos.pop();
                 String rotuloInicio = pilhaRotulos.pop();
                 gerador.emitir("JMP", rotuloInicio);
                 gerador.emitirRotulo(rotuloFim);
             
              CUP$parser$result = parser.getSymbolFactory().newSymbol("enquanto",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // NT$7 ::= 
            {
              Object RESULT =null;
 gerador.emitirComentario("comando for: inicializacao"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$7",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // NT$8 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;

             gerador.emitirComentario("comando for: teste da condicao");
             String rotuloTeste = gerador.novoRotulo();
             gerador.emitirRotulo(rotuloTeste);
             pilhaRotulos.push(rotuloTeste);
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$8",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // NT$9 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AtributosExpressao c = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

             semantico.verificarCondicao(c.tipo, "for", cleft, cright);
             String rotuloFim = gerador.novoRotulo();
             gerador.emitir("JMPF", c.registrador + ", " + rotuloFim);
             pilhaRotulos.push(rotuloFim);
             gerador.iniciarCaptura();
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$9",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // NT$10 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		AtributosExpressao c = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
 pilhaIncremento.push(gerador.encerrarCaptura()); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$10",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // para ::= FOR NT$7 LPAR atrib NT$8 expr SEMI NT$9 atrib_inc NT$10 RPAR bloco 
            {
              Object RESULT =null;
              // propagate RESULT from NT$10
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		AtributosExpressao c = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		
             gerador.emitirComentario("comando for: incremento");
             gerador.emitirTrecho(pilhaIncremento.pop());
             String rotuloFim = pilhaRotulos.pop();
             String rotuloTeste = pilhaRotulos.pop();
             gerador.emitir("JMP", rotuloTeste);
             gerador.emitirRotulo(rotuloFim);
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("para",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-11)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // escrever ::= PRINTF LPAR expr RPAR SEMI 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AtributosExpressao e = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 gerador.emitir("WRITE", e.registrador); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("escrever",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // ler ::= SCANF LPAR ID RPAR SEMI 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
                 semantico.usar(i, ileft, iright);
                 gerador.emitir("READ", semantico.rotuloDe(i));
             
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ler",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expr ::= expr PLUS expr 
            {
              AtributosExpressao RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AtributosExpressao a = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AtributosExpressao b = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = calcular("+", "ADD", a, b, aleft, aright); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expr ::= expr MINUS expr 
            {
              AtributosExpressao RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AtributosExpressao a = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AtributosExpressao b = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = calcular("-", "SUB", a, b, aleft, aright); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expr ::= expr TIMES expr 
            {
              AtributosExpressao RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AtributosExpressao a = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AtributosExpressao b = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = calcular("*", "MUL", a, b, aleft, aright); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expr ::= expr DIV expr 
            {
              AtributosExpressao RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AtributosExpressao a = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AtributosExpressao b = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = calcular("/", "DIV", a, b, aleft, aright); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expr ::= expr EQ expr 
            {
              AtributosExpressao RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AtributosExpressao a = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AtributosExpressao b = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = comparar("==", "CMPEQ", a, b, aleft, aright); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expr ::= expr NEQ expr 
            {
              AtributosExpressao RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AtributosExpressao a = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AtributosExpressao b = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = comparar("!=", "CMPNE", a, b, aleft, aright); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expr ::= expr LT expr 
            {
              AtributosExpressao RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AtributosExpressao a = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AtributosExpressao b = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = comparar("<",  "CMPLT", a, b, aleft, aright); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expr ::= expr GT expr 
            {
              AtributosExpressao RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AtributosExpressao a = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AtributosExpressao b = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = comparar(">",  "CMPGT", a, b, aleft, aright); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expr ::= expr LEQ expr 
            {
              AtributosExpressao RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AtributosExpressao a = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AtributosExpressao b = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = comparar("<=", "CMPLE", a, b, aleft, aright); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expr ::= expr GEQ expr 
            {
              AtributosExpressao RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AtributosExpressao a = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AtributosExpressao b = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = comparar(">=", "CMPGE", a, b, aleft, aright); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expr ::= expr AND expr 
            {
              AtributosExpressao RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AtributosExpressao a = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AtributosExpressao b = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = combinar("&&", "AND", a, b, aleft, aright); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expr ::= expr OR expr 
            {
              AtributosExpressao RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AtributosExpressao a = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AtributosExpressao b = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = combinar("||", "OR",  a, b, aleft, aright); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expr ::= MINUS expr 
            {
              AtributosExpressao RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AtributosExpressao a = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
             String t = semantico.verificarNegativo(a.tipo, aleft, aright);
             String destino = gerador.novoRegistrador();
             gerador.emitir("NEG", destino + ", " + a.registrador);
             RESULT = new AtributosExpressao(t, destino);
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expr ::= NOT expr 
            {
              AtributosExpressao RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AtributosExpressao a = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
             String t = semantico.verificarNegacao(a.tipo, aleft, aright);
             String destino = gerador.novoRegistrador();
             gerador.emitir("NOT", destino + ", " + a.registrador);
             RESULT = new AtributosExpressao(t, destino);
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expr ::= termo 
            {
              AtributosExpressao RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AtributosExpressao t = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = t; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // termo ::= ID 
            {
              AtributosExpressao RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
              String t = semantico.usar(i, ileft, iright);
              String destino = gerador.novoRegistrador();
              gerador.emitir("LOAD", destino + ", " + semantico.rotuloDe(i));
              RESULT = new AtributosExpressao(t, destino);
          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("termo",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // termo ::= NUM_INT 
            {
              AtributosExpressao RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer v = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
              String destino = gerador.novoRegistrador();
              gerador.emitir("LOADI", destino + ", " + v);
              RESULT = new AtributosExpressao("int", destino);
          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("termo",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // termo ::= NUM_REAL 
            {
              AtributosExpressao RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double v = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
              String destino = gerador.novoRegistrador();
              gerador.emitir("LOADI", destino + ", " + v);
              RESULT = new AtributosExpressao("real", destino);
          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("termo",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // termo ::= LIT_CHR 
            {
              AtributosExpressao RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
              String destino = gerador.novoRegistrador();
              gerador.emitir("LOADI", destino + ", " + v);
              RESULT = new AtributosExpressao("chr", destino);
          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("termo",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // termo ::= LIT_STR 
            {
              AtributosExpressao RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
              String destino = gerador.novoRegistrador();
              gerador.emitir("LOADI", destino + ", " + v);
              RESULT = new AtributosExpressao("str", destino);
          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("termo",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // termo ::= TRUE 
            {
              AtributosExpressao RESULT =null;
		
              String destino = gerador.novoRegistrador();
              gerador.emitir("LOADI", destino + ", 1");
              RESULT = new AtributosExpressao(AnalisadorSemantico.LOGICO, destino);
          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("termo",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // termo ::= FALSE 
            {
              AtributosExpressao RESULT =null;
		
              String destino = gerador.novoRegistrador();
              gerador.emitir("LOADI", destino + ", 0");
              RESULT = new AtributosExpressao(AnalisadorSemantico.LOGICO, destino);
          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("termo",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // termo ::= LPAR expr RPAR 
            {
              AtributosExpressao RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AtributosExpressao e = (AtributosExpressao)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("termo",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
